name: nlp-project-env-conda
dependencies:
  - python==3.8
  - pip
  - pip:
    - torch==1.9.0
    - torchvision==0.10.0
    - torchaudio==0.9.0
    - pytorch-lightning==1.3.0
    - ipykernel
    - torchmetrics>=0.3
    - transformers
    - scikit-learn
    #- torch>=1.6, <1.9
    - pytorch-lightning>=1.3
    - lightning-bolts==0.4.0
    - datasets
    - scipy
    # - cudatoolkit==10.2
    - tensorboard
    - wandb == 0.12.5
    - sapcy
    - sacrebleu
    - textdistance